#!/usr/bin/env node
/**
 * Fetches the IC Promotion Wiki page using the user's Midway session
 * and writes a TypeScript module with the HTML content for offline use.
 *
 * Usage: node scripts/sync-wiki.mjs
 * Requires: active Midway session (run `mwinit` first)
 */
import { execSync } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = resolve(__dirname, '..');

const WIKI_URL =
  'https://w.amazon.com/bin/view/ITSERVICES/guest-speaker/templates/drafts/ic-promotion-wiki/?xpage=plain';
const HUMAN_URL =
  'https://w.amazon.com/bin/view/ITSERVICES/guest-speaker/templates/drafts/ic-promotion-wiki';
const COOKIE_PATH = `${process.env.HOME}/.midway/cookie`;
const OUTPUT_DIR = resolve(PROJECT_ROOT, 'src/content');
const OUTPUT_FILE = resolve(OUTPUT_DIR, 'guidelines-wiki.ts');

console.log('🔄 Fetching IC Promotion Wiki...');

let html;
try {
  // Prefer mcurl (Midway-aware curl) if available; fall back to curl with cookie jar
  const hasMcurl = (() => {
    try { execSync('which /usr/local/bin/mcurl', { stdio: 'ignore' }); return true; } catch { return false; }
  })();
  const cmd = hasMcurl
    ? `mcurl -sL "${WIKI_URL}"`
    : `curl -sL -b "${COOKIE_PATH}" "${WIKI_URL}"`;
  html = execSync(cmd, { encoding: 'utf-8', maxBuffer: 10 * 1024 * 1024 });
} catch (err) {
  console.error('❌ Failed to fetch wiki page. Run mwinit first.');
  process.exit(1);
}

// Detect auth redirect — Midway returns a redirect to midway-auth/federate when cookie is expired
if (
  html.includes('midway-auth') ||
  html.includes('/federate') ||
  html.includes('"status":"error"') ||
  html.includes('Unauthenticated') ||
  !html.includes('<') // not HTML at all
) {
  console.error('❌ Midway session expired or invalid. Run mwinit first.');
  process.exit(1);
}

// Escape the HTML for embedding inside a JS template literal:
// - backticks become \` so they don't terminate the template
// - ${ becomes \${ so template expressions aren't evaluated
const escaped = html
  .replace(/\\/g, '\\\\')   // escape existing backslashes first
  .replace(/`/g, '\\`')     // escape backticks
  .replace(/\$\{/g, '\\${'); // escape template expression starts

const now = new Date().toISOString();

const content = `// AUTO-GENERATED by scripts/sync-wiki.mjs — do not edit
export const WIKI_HTML = \`${escaped}\`;

export const WIKI_SYNCED_AT = '${now}';

export const WIKI_SOURCE_URL = '${HUMAN_URL}';
`;

mkdirSync(OUTPUT_DIR, { recursive: true });
writeFileSync(OUTPUT_FILE, content, 'utf-8');

const sizeKB = (Buffer.byteLength(content, 'utf-8') / 1024).toFixed(1);
console.log(`✅ Written ${OUTPUT_FILE} (${sizeKB} KB)`);
console.log(`   Synced at: ${now}`);
